### PR TITLE
Stoconnor patch 4

### PR DESCRIPTION
**Pull request by stoconnor**

### CODE REVIEW

**Review by sdesalve — COMMENTED** [review]
Have you successfully runned Monocle Gateway on armv7?

Is Monocle executable now compatible with HassOS - Alpine Linux?
What's your hardware? On my Raspberry 3b+ with HassOS it doesn't run

If it works I'll accept your contribution. But please restore link to my GitHub

**Comment by stoconnor** [comment]
Sorry I was editing a file on my mobile and the PR went to your repo instead of mine. Testing armv7 now, I had to switch repo url to the forked instance for now. I'll keep you updated

**Comment by sdesalve** [comment]
Unfortunately will not run on HassOS armv7.

Gateway is closed source and developer has not yet released a compatible version

**Comment by stoconnor** [comment]
There is an armv7 build of the monocle gateway available, that should work?

**Comment by stoconnor** [comment]
https://monoclecam.com/monocle-gateway/install/linux-arm

**Comment by sdesalve** [comment]
No, I wasn't able to make it run.

But search thread on Monocle forums

**Comment by sdesalve** [comment]
Could you try to install this?
https://github.com/sdesalve/hassio-addons/tree/master/dss_monocle-gateway-beta

**Pull request closed without merging**
